type: operation
description:
title:
label: "Generate Certificate Signing Request and Private Key from custom OpenSSL configuration file"
entry_point:
  module: operation.manage_certificate
  method: generate_csr_and_private_key
arguments:
  - name: cert_usage
    value: "sso-sts"
  - name: custom_openssl_config
    value: true
