type: operation-group
description: "Manage CA certificate in the SMS VECS Store"
title:
label: "SMS certificates"
operations:
  - type: single
    config: "config/op_prevalidate_credential.yaml"
  - type: single
    entry_point:
      module: "operation.manage_certificate"
      method: "manage_sms_certificates"