type: operation-group
description: "Operation for checking certificates status"
title: "Check current certificates status"
operations:
  - type: single
    config: "config/op_prevalidate_credential.yaml"
  - type: multiple
    config: "config/check_cert/op_*.yaml"
