type: operation-group
description: "Check SSL trust anchors"
title:
label: "Show associated endpoint URIs"
operations:
  - type: single
    config: "config/op_prevalidate_credential.yaml"
  - type: single
    entry_point:
      module: "operation.manage_certificate"
      method: "check_ssl_trust_anchors"
    arguments:
      - name: "show_endpoint_uris"
        value: true

