type: operation-group
description: "Manage CA certificate in VECS"
title:
label: "CA certificates in VECS Directory"
operations:
  - type: single
    config: "config/op_prevalidate_credential.yaml"
  - type: single
    entry_point:
      module: "operation.manage_certificate"
      method: "manage_ca_certificates_in_vecs"
