type: operation-group
description: 'Manage LDAPS Identity Source certificates'
title:
label: 'LDAPS Identity Source certificates'
condition: 'HAS_LDAPS_IDENTITY_SOURCE'
operations:
  - type: single
    config: 'config/op_prevalidate_credential.yaml'
  - type: single
    entry_point:
      module: 'operation.manage_certificate'
      method: 'manage_ldaps_identity_source_certificates'