type: menu
description:
title: "Manage ESXi Certificates"
label: "ESXi certificate operations"
items:
  - type: multiple
    config: "config/esxi_cert_actions/op_esxi_action*.yaml"
  - type: navigation:return
    label: "Return to main menu"
    key: "R"
    default: True
    hidden: true
    use_label_as_key: True