type: menu
description: "Operation for restarting services"
title: "Restart VMware Services"
label: "Restart services"
items:
  - type: multiple
    config: "config/restart_service/op_restart_*.yaml"
  - type: navigation:return
    label: "Return to main menu"
    key: "R"
    default: True
    use_label_as_key: True
    hidden: True
