type: operation-group
description:
title:
label: "Replace Machine SSL certificate with a VMCA-signed certificate"
operations:
  - type: single
    config: "config/op_prevalidate_credential.yaml"
  - type: single
    entry_point:
      module: "operation.manage_certificate"
      method: "manage_machine_ssl_certificate_with_vmca_signed"
